repos:
  - repo: local
    hooks:
    - id: fix-latin-abbrev
      name: Fix Latin abbreviations (e.g., i.e.)
      entry: sed -i -e 's/\(\<\(e\.g\.\|i\.e\.\)\) /\1, /g'
      language: system
      files: ^.*/.*\.md$
      types: [markdown]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      additional_dependencies:
        - tomli
      files: ^.*\.(py|md|)$
      args: ["--ignore-words", "project-words.txt" ]
